window.BOOKLET_DATA={lessons:[
['start','2','🧺','أجزاء الكلام','أتعرف وظيفة الكلمة داخل الجملة.','👧 The happy girl runs quickly.','Noun • Verb • Pronoun • Adjective • Adverb • Preposition','الاسم يسمّي، والفعل يخبرنا بالحدث، والضمير يحل محل الاسم، والصفة تصف اسمًا، والحال يصف كيفية الفعل، وحرف الجر يربط الأفكار.',['The dog runs quickly.','Sara is a kind friend.'],['Which word is a verb?','plays',['school','plays','happy'],'plays تخبرنا بالحدث، فهي فعل.']],
['start','3','👥','ضمائر الفاعل','أستبدل الاسم بضمير مناسب.','Sara → she　Ali and Omar → they','I • you • he • she • it • we • they','I مفرد لكنه يأخذ أصل الفعل. you للمفرد والجمع. it للأشياء والحيوانات، ويمكن he/she للحيوان إن عُرف جنسه.',['I play. She plays.','The books are new. They are new.'],['Sara and Mona → ?','they',['she','they','we'],'اسمان فأكثر من الغائبين = they.']],
['words','4–5','📍','حروف الجر','أصف المكان والحركة والوقت.','📦 in the box　➡️ into the box','place • movement • time • other uses','in موقع داخل شيء، أما into فحركة إلى الداخل. لا نربط كل حرف بترجمة عربية واحدة؛ نقرأه في السياق.',['at 8 • on Monday • in 2026','between • next to • under'],['The cat jumps ___ the box.','into',['in','into','during'],'توجد حركة إلى الداخل، لذا into.']],
['words','6–7','🧮','المفرد والجمع','أجمع الأسماء بأنماط صحيحة.','📦 box → boxes　📖 story → stories','s • es • consonant+y → ies • irregular','نضيف s غالبًا، وes بعد s/ch/sh/x/z. إذا سبق y حرف ساكن تصبح ies. توجد صيغ شاذة. mangos وmangoes صحيحتان.',['pen → pens • quiz → quizzes','toy → toys • child → children'],['Plural of story:','stories',['storys','stories','storyes'],'قبل y حرف ساكن، نحذف y ونضيف ies.']],
['words','8','🔎','a / an / the','أقدم شيئًا ثم أشير إليه.','I see a cat. The cat is small.','a/an + singular countable • the + specific','نختار a أو an حسب الصوت التالي، لا الحرف: an hour لكن a university.',['an apple • an hour','a book • a university'],['Choose: ___ hour','an',['a','an','the'],'hour تبدأ بصوت علة لأن h صامتة.']],
['words','9','🎨','الصفات','أصف اسمًا قبل الاسم أو بعد be.','a tall boy　•　The boy is tall.','adjective + noun • be + adjective','الصفة قد تأتي قبل الاسم أو بعد be. لا نجمعها بإضافة s: smart boys.',['a clever girl','The flowers are beautiful.'],['Choose the correct phrase.','smart boys',['smarts boys','smart boys','boys smartes'],'الصفة الإنجليزية لا تأخذ s للجمع.']],
['words','10','🏃','الأحوال','أصف كيف يحدث الفعل.','a careful driver　•　He drives carefully.','quick→quickly • good→well • fast→fast','بعض الأحوال تنتهي بـly وبعضها لا، وموضع الحال ليس ثابتًا دائمًا بعد الفعل. bad→badly؛ worse صيغة مقارنة.',['She speaks quietly.','He runs fast. He works hard.'],['He is good. He plays ___.','well',['good','well','worse'],'حال good هو well.']],
['words','11','🏗️','بناء الجملة','أبني جملة واضحة بأكثر من نمط.','فاعل + فعل + ما تحتاجه الفكرة','S+V • S+V+O • S+be+adjective/noun','ليست كل جملة بحاجة إلى مفعول. في Ahmed is a doctor، is فعل ربط وdoctor اسم.',['Birds fly.','Lina reads a book.','Ahmed is a doctor.'],['In “Ahmed is a doctor”, doctor is a…','noun',['verb','noun','adverb'],'doctor يسمّي مهنة، لذلك هو اسم.']],
['tenses','12','🔁','المضارع البسيط','أتحدث عن عادة أو حقيقة.','every day ☀️ I play. She plays.','I/you/we/they + base • he/she/it + s/es/ies','مع النفي والسؤال نستخدم do/does ويعود الفعل إلى أصله. every day كلمتان عندما تعني كل يوم.',["She doesn’t play.",'Does she play?'],['Choose the correct sentence.','She plays every day.',['She play every day.','She plays every day.','She does plays every day.'],'مع she في الإثبات نضيف s.']],
['tenses','13','🕰️','الماضي البسيط','أتحدث عن حدث انتهى.','yesterday ← played / went / met','past • did/didn’t + base • was/were','المنتظم يأخذ d/ed/ied، وبعض الأفعال غير منتظمة. used to تركيب خاص لعادات أو حالات سابقة.',['She came late yesterday.','Did you go? I didn’t go.'],['Complete: Did he ___ Ali?','meet',['met','meet','meets'],'بعد did نستخدم أصل الفعل meet.']],
['tenses','14','🔮','المستقبل بـ will','أعبر عن قرار أو وعد أو توقع.','📞 I’ll answer the phone!','will / won’t + base • Will …?','will لقرار أثناء الحديث أو وعد أو توقع مناسب، لكنه ليس الطريقة الوحيدة للتعبير عن المستقبل.',["I’ll help you.",'Will it rain? It won’t rain.'],['Complete: She will ___ us.','visit',['visits','visit','visited'],'بعد will نستخدم أصل الفعل.']],
['tenses','15','▶️','المضارع المستمر','أصف ما يحدث الآن أو مؤقتًا.','NOW: 🏃 He is running.','am/is/are + verb-ing','التصحيح العلمي: فعل يحدث الآن أو نشاط مؤقت، وليس تعريف المستقبل المنسوخ في الكتيب.',['I am eating now.','They aren’t playing.','Is he sleeping?'],['Right now, they ___ playing.','are',['do','are','will'],'نحتاج are + ing مع they.']],
['tenses','16','🎞️','الماضي المستمر','أصف حدثًا كان جاريًا في الماضي.','📖 was reading　🔔 bell rang','was/were + verb-ing','حدث كان مستمرًا في وقت ماضٍ أو وقع أثناءه حدث آخر، دون تعميم قالب when.',['I was reading when the bell rang.','Were they sleeping?'],['At 8 pm, we ___ watching TV.','were',['was','were','did'],'مع we نستخدم were.']],
['tenses','17','⏩','المستقبل المستمر','أصف فعلًا سيكون جاريًا لاحقًا.','tomorrow at 8 ➡️ will be studying','will be + verb-ing','مستوى متقدم: will study يذكر الفعل، وwill be studying يركز على استمراره عند وقت محدد.',['I will be studying.','Will you be sleeping?'],['Tomorrow at 8, I ___ travelling.','will be',['will','will be','was'],'الجاري مستقبلًا: will be + ing.']],
['questions','18–20','🧰','be / do / have','أميز الفعل الأساسي من المساعد.','I do homework.　Do you play?','be: am/is/are–was/were–been • do–did–done • have–had–had','قد تكون أفعالًا أساسية أو مساعدة: I have a pencil (أساسي)، She is reading (مساعد).',['She is happy.','Do you play?','I have a pencil.'],['In “Do you play?”, do is…','an auxiliary',['a noun','an auxiliary','an adjective'],'do يساعد في صناعة السؤال.']],
['questions','21','🔍','أدوات الاستفهام','أختار أداة السؤال المناسبة.','What? When? Where? Why? Who? How? Which?','question word + suitable pattern','لا يوجد قالب واحد دائمًا: Where are you? وWhen did you arrive? أما سؤال الفاعل: Who came?',['Why are you late?','Which book do you want?'],['___ do you live?','Where',['When','Where','Who'],'Where تسأل عن المكان.']],
['questions','22–23','❓','صناعة الأسئلة','أصنع سؤال نعم/لا أو معلومات.','Are you busy?　When did you sleep?','be…? • do/does/did…? • will…?','مع be نقدمه، ومع الفعل العادي نستخدم do/does/did، ومع المستقبل will. سؤال الفاعل Who came? لا يحتاج do.',['Does she play? Yes, she does.','When did you sleep?'],['Choose the correct question.','Where does he live?',['Where he lives?','Where does he live?','Where is he live?'],'الأداة ثم does ثم الفاعل ثم أصل الفعل.']]
],games:[['🧺 أجزاء الكلام','small is…','adjective',['noun','adjective','verb'],'small تصف اسمًا.'],['👥 الضمير','Ali and I →','we',['they','we','you'],'المتكلم مع آخر = we.'],['📍 المكان','The ball is ___ the boxes.','between',['under','between','into'],'between بين شيئين.'],['🧮 الجمع','Plural of quiz:','quizzes',['quizs','quizes','quizzes'],'نضيف es ونضاعف z.'],['🔎 الأدوات','I saw ___ elephant.','an',['a','an','the'],'يبدأ بصوت علة.'],['🎨 الصفة','Choose the adjective.','careful',['carefully','careful','care'],'careful صفة.'],['🏃 الحال','She sings ___.','beautifully',['beautiful','beautifully','beauty'],'يصف كيفية الغناء.'],['🏗️ الجملة','Choose a sentence.','Birds fly.',['Birds.','Fly birds the.','Birds fly.'],'فاعل وفعل كافيان.'],['🧰 المساعد','___ she play?','Does',['Is','Does','Did yesterday'],'مضارع مع she: Does.'],['🔁 الآن','Look! He ___.','is running',['runs every day','is running','ran'],'Look يدل على ما يحدث الآن.'],['⏳ الزمن','Which is past?','They went home.',['They go home.','They went home.','They will go home.'],'went ماضٍ.'],['🚫 النفي','Negative: She plays.','She doesn’t play.',["She don’t plays.","She doesn’t play.","She not play."],'doesn’t + أصل الفعل.'],['🎞️ المشهد','At 9 yesterday, I ___ reading.','was',['am','was','will be'],'وقت ماضٍ: was + ing.'],['❓ الترتيب','Arrange.','Where do you live?',['Where you do live?','Where do you live?','Do where you live?'],'الأداة ثم المساعد فالفاعل.'],['🔗 الجواب','Why are you happy?','Because it is my birthday.',['At school.','Because it is my birthday.','On Monday.'],'Why تطلب سببًا.'],['🧯 أصلح','He don’t play.','He doesn’t play.',["He doesn’t play.","He don’t plays.","He isn’t play."],'مع he: doesn’t.'],['👂 استمع','Listen.','The children are playing quietly.',['The children play every day.','The children are playing quietly.','The child is playing quickly.'],'استمع للفاعل والزمن والحال.'],['🌟 مختلط','___ you be studying at 8?','Will',['Do','Will','Are'],'المستقبل المستمر يبدأ Will.']]};

