window.GRAMMAR_DATA={
 foundations:[['👥','الضمائر','I, you, he, she, it, we, they','She is my friend.'],['🧩','أجزاء الجملة','فاعل + فعل، والصفة تصف','The bird flies. It is fast.'],['🔵','فعل be','I am • he/she/it is • you/we/they are','We are ready.'],['❓','إثبات، نفي، سؤال','نغيّر شكل الجملة حسب الغرض','Is she happy? She isn’t sad.'],['🛠️','الفعل المساعد','يساعدنا على السؤال والنفي','Does he play? He doesn’t play.'],['🪜','صور الفعل','base • past • participle • ing','write • wrote • written • writing'],['⏳','خط الزمن','الآن، الماضي، المستقبل','I play. I played. I will play.']],
 units:[
  [1,'📏','المقارنة والمهارات','أقارن بين شخصين أو أكثر وأتحدث عن المهارات.','PDF ص1 • Unit 1','👧 short　👩 shorter　👵 the shortest','short → shorter than → the shortest','المقارنة بين اثنين، وthe + التفضيل داخل مجموعة. الصفات الأطول قد تستخدم more وthe most؛ لا يعتمد ذلك على عدد الحروف وحده.',['My mum is shorter than me.','Mona is the most hard-working student.','I am good at drawing.'],[['more taller','taller'],['the most tallest','the tallest'],['good at draw','good at drawing']],['Choose the correct sentence.','Ali is taller than Sami.',['Ali is more taller than Sami.','Ali is taller than Sami.','Ali is the tallest than Sami.']]],
  [2,'🕰️','الماضي والقدرة','أتحدث عما كان وما حدث وما استطعت فعله.','PDF ص1 • Unit 2','👶 couldn’t talk　➡️　🧒 can talk','was / were • did + base • could + base','Was/Were للحالة: Was he happy? أما did فللفعل: Did he play? وبعد did وcould نستخدم أصل الفعل.',['We were at home.','Did you have a phone?','She could swim.'],[['Did you had…?','Did you have…?'],['She could swam.','She could swim.']],['Choose the correct question.','Did you have a bike?',['Did you had a bike?','Did you have a bike?','Were you have a bike?']]],
  [3,'🎁','المستقبل والقياس','أقول قرارًا مستقبليًا وأسأل عن القياس.','PDF ص1 • Unit 3','🎂 Tomorrow　➡️　🎁 I’ll buy a book.','will / won’t + base verb','will لقرار أو حدث مستقبلي. في القياس: العدد + الوحدة + الصفة. How tall/long/wide توسع تعليمي.',["I’ll get him a present.","What will you buy?","It’s 1,800 metres deep."],[['She will buys it.','She will buy it.']],['Complete: What ___ you buy?','will',['did','will','are']]],
  [4,'🔗','الربط والضرورة','أربط الأفكار وأوضح ما هو ضروري.','PDF ص1 • Unit 4','👨 who　📱 which　🏪 where','person + who • thing + which • place + where','who للشخص، which للشيء، where للمكان. don’t have to تعني ليس ضروريًا، أما mustn’t فتعني ممنوعًا.',['The man who works here is kind.','This is the shop where Mum works.','He doesn’t have to buy it.'],[['Does he has to…?','Does he have to…?'],["don’t have to = forbidden","don’t have to = not necessary"]],['Choose the word for a place.','where',['who','which','where']]],
  [5,'🎬','الماضي المستمر','أصف حدثًا كان جاريًا في وقت ماضٍ.','PDF ص1 • Unit 5','📖 I was reading　🔔 when the bell rang.','was / were + verb-ing','يرسم حدثًا جاريًا في الماضي. قد يقع أثناءه حدث قصير، لكن ليس كل ما بعد when ماضيًا بسيطًا.',['The shark was looking for fish.','We weren’t watching the lion.','What were you doing?'],[['They was playing.','They were playing.']],['Complete: We ___ watching the koalas.','were',['was','were','did']]],
  [6,'💡','النصيحة والغرض','أقدم نصيحة وأشرح لماذا أفعل شيئًا.','PDF ص2 • Unit 6','✏️ I use a pencil to write.','should + base • to + base (purpose)','should نصيحة وليست إلزامًا. to + أصل الفعل يشرح الغرض. قارن good at drawing مع to draw.',['You should rest.','You shouldn’t be late.','He went to buy fruit.'],[['You should to go.','You should go.']],['Complete: I use scissors ___ cut paper.','to',['for','to','at']]],
  [7,'🌟','المضارع التام','أتحدث عن تجربة أو نتيجة مرتبطة بالحاضر.','PDF ص2 • Unit 7','🎭 Have you ever been to a concert?','have / has + past participle','للتجارب والنتائج المهمة الآن، وليس فقط «ماضٍ بلا وقت». I’ve = I have وHe’s seen = He has seen. for ages = منذ زمن طويل.',["I’ve read the book.","He hasn’t found it.","Have you ever been to a concert?"],[['She have seen it.','She has seen it.']],['Complete: He ___ seen the film.','has',['have','has','did']]],
  [8,'🧱','التجارب ومواد الصنع','أسأل عن تجربة وأصف مادة صنع الأشياء.','PDF ص2 • Unit 8','🧸 What is it made of? — It is made of plastic.','have never + participle • is/are made of','never بين have/has والتصريف الثالث بلا نفي مزدوج. made جزء من التركيب ولا يجعل الجملة ماضية وحده.',["She’s never used the oven.",'It is made of plastic.','They are made of gold.'],[["I haven’t never…","I have never…"]],['Complete: They ___ made of wood.','are',['is','are','have']]],
  [9,'🌍','التجربة ووقتها والشرط','أفرق بين التجربة ووقتها وأربط حقيقة بشرط.','PDF ص2 • Unit 9','🇮🇹 I’ve been to Italy. I went last month.','Have you ever…? → When did…? • If + present, present','المضارع التام يذكر التجربة ثم الماضي البسيط يحدد وقتها. الشرط الصفري يصف نتيجة عامة متكررة.',["I’ve been to Italy.",'I went there last month.','If you go inside a cave, you need a torch.'],[['I have been there last month.','I went there last month.']],['Choose the general result.','If water freezes, it becomes ice.',['If water freezes, it will become ice tomorrow.','If water freezes, it becomes ice.','If water froze, it becomes ice.']]]
 ],
 verbs:[['be','was/were','been','يكون','different'],['buy','bought','bought','يشتري','pastpp'],['do','did','done','يفعل','different'],['drink','drank','drunk','يشرب','different'],['eat','ate','eaten','يأكل','different'],['find','found','found','يجد','pastpp'],['get','got','got','يحصل على','pastpp'],['give','gave','given','يعطي','different'],['go','went','gone','يذهب','different'],['have','had','had','يملك','pastpp'],['know','knew','known','يعرف','different'],['lose','lost','lost','يفقد','pastpp'],['make','made','made','يصنع','pastpp'],['put','put','put','يضع','same'],['run','ran','run','يركض','basepp'],['see','saw','seen','يرى','different'],['sell','sold','sold','يبيع','pastpp'],['send','sent','sent','يرسل','pastpp'],['sing','sang','sung','يغني','different'],['sleep','slept','slept','ينام','pastpp'],['take','took','taken','يأخذ','different'],['tell','told','told','يخبر','pastpp'],['wear','wore','worn','يرتدي','different'],['write','wrote','written','يكتب','different'],['read','read','read','يقرأ','support']],
 games:[['📏 مقارنة','Choose the correct comparison.','The blue rope is longer than the red rope.',['The blue rope is more long.','The blue rope is longer than the red rope.','The blue rope is longest than.'],'longer than للمقارنة بين شيئين.'],['⏳ الأزمنة','Which sentence is in the future?','I will visit my aunt.',['I visited my aunt.','I visit my aunt.','I will visit my aunt.'],'will + أصل الفعل للمستقبل.'],['🧯 أصلح الخطأ','Fix: She could swam.','She could swim.',['She could swim.','She can swam.','She could swimming.'],'بعد could نستخدم أصل الفعل.'],['🛠️ المساعد','___ you play yesterday?','Did',['Were','Did','Have'],'نسأل عن فعل ماضٍ باستخدام Did.'],['🔗 الربط','A nurse is a person ___ helps people.','who',['which','where','who'],'who للشخص.'],['💬 النصيحة','It is a good idea, but not a rule.','should',['have to','should','mustn’t'],'should للنصيحة.'],['🎬 المشهد','At 8 o’clock, they ___ sleeping.','were',['was','were','did'],'مع they نستخدم were.'],['🎯 الغرض','I use a camera ___ take photos.','to',['to','at','for'],'to + أصل الفعل للغرض.'],['🌟 تجربة','___ you ever seen snow?','Have',['Did','Have','Were'],'Have + subject + participle.'],['🧱 المواد','The bottle ___ made of glass.','is',['has','is','are'],'bottle مفرد: is made of.'],['🔁 الشرط','If plants don’t get water, they ___.','die',['will died','die','died'],'المضارع في جزأي الشرط الصفري.'],['⚗️ تصريف','Past participle of write:','written',['wrote','written','writed'],'التصريف الثالث written.'],['👂 استماع','Listen, then choose.','She has never been to Italy.',['She has never been to Italy.','She never went Italy.','She is going Italy.'],'never بعد has وقبل been.']]
};

